Repository vircadia/vircadia-web-sdk, pull requests merged in 2021-12, with the labels that each got.

#67 Fix build error.
  src/domain/networking/udt/Socket.ts
Labels: bugfix

#68 Log certain warnings only once.
  src/domain/audio-client/AudioClient.ts
  src/domain/audio/InboundAudioStream.ts
Labels: enhancement, CR approved

#69 Remove unused code in Audio worklets.
  src/domain/worklets/AudioInputProcessor.ts
  src/domain/worklets/AudioOutputProcessor.ts
Labels: housekeeping

#70 Overriding properties of test.config.json with environment variables.
  README.md
  tests/AudioMixer.integration.test.js
  tests/AvatarMixer.integration.test.js
  tests/DomainServer.integration.test.js
  tests/MessageMixer.integration.test.js
  tests/domain/AssignmentClient.integration.test.js
  tests/domain/networking/AddressManager.unit.test.js
  tests/domain/networking/DomainHandler.unit.test.js
  tests/domain/networking/udt/Socket.integration.test.js
  tests/domain/networking/udt/Socket.unit.test.js
  tests/domain/networking/webrtc/WebRTCDataChannel.integration.test.js
  tests/domain/networking/webrtc/WebRTCSignalingChannel.integration.test.js
  tests/domain/networking/webrtc/WebRTCSocket.integration.test.js
  tests/test.config.js
Labels: enhancement, CR approved

#71 Fix lint error.
  src/domain/audio/InboundAudioStream.ts
Labels: bugfix

#60 Add build versioning to SDK.
  .eslintignore
  .gitignore
  CONFIGURATION.md
  README.md
  build_scripts/cleanDist.js
  build_scripts/createVersion.js
  package-lock.json
  package.json
  src/Vircadia.ts
  tsconfig.json
Labels: enhancement

#73 Increment version number to 2022.1.1.
  package.json
Labels: enhancement, CR approved

#74 Update developer setup instructions.
  README.md
Labels: enhancement, CR approved

#75 Make audio worklets able to be loaded from a relative path.
  example/interface.js
  jest.config.js
  mocks/domain/audio/AudioWorklets.mock.js
  mocks/worker-url.mock.js
  mocks/worklet-loader.mock.js
  package-lock.json
  package.json
  src/AudioMixer.ts
  src/domain/audio-client/AudioClient.ts
  src/domain/audio/AudioInput.ts
  src/domain/audio/AudioOutput.ts
  src/domain/audio/AudioWorklets.ts
  tests/AudioMixer.integration.test.js
  tests/AudioMixer.unit.test.js
  tests/Vircadia.integration.test.js
  tests/Vircadia.unit.test.js
  tests/domain/audio-client/AudioClient.unit.test.js
  tests/domain/audio/AudioInput.unit.test.js
  tests/domain/audio/AudioOutput.unit.test.js
  tests/domain/audio/InboundAudioStream.unit.test.js
  tests/domain/avatars/AvatarData.unit.test.js
  tests/domain/shared/SpatiallyNestable.unit.test.js
  tsconfig.jsdoc.json
  tsconfig.json
  typings/WorkletLoaderTyping.d.ts
  webpack.config.js
Labels: enhancement, CR approved, QA approved

#79 Add SDK packaging instructions and update .gitignore.
  .gitignore
  README.md
Labels: enhancement, CR approved

#81 Fix AudioMixer.audioOutput property name.
  example/interface.js
  src/AudioMixer.ts
  src/domain/audio/AudioOutput.ts
Labels: bugfix, CR approved, QA approved

#82 Add missing packet details links to packet type list.
  src/domain/networking/udt/PacketHeaders.ts
Labels: bugfix, CR approved, docs

#80 Add avatar orientations in MyAvatarInterface and AvatarListInterface.
  example/interface.html
  example/interface.js
  src/domain/avatar-renderer/ScriptAvatar.ts
  src/domain/avatars/AvatarData.ts
  src/domain/avatars/AvatarHashMap.ts
  src/domain/interfaces/MyAvatarInterface.ts
  src/domain/networking/packets/AvatarData.ts
  src/domain/networking/packets/BulkAvatarData.ts
  src/domain/shared/GLMHelpers.ts
  src/domain/shared/SpatiallyNestable.ts
  tests/domain/avatar-renderer/ScriptAvatar.unit.test.js
  tests/domain/networking/packets/AvatarData.unit.test.js
  tests/domain/networking/packets/BulkAvatarData.unit.test.js
  tests/domain/shared/GLMHelpers.unit.test.js
  tests/domain/shared/SpatiallyNestable.unit.test.js
Labels: enhancement, CR approved
