Repository vircadia/vircadia-web-sdk, pull requests merged in 2022-07, with the labels that each got.

#127 Reduce number of OctreePacketProcessor warnings logged.
  src/domain/networking/udt/PacketHeaders.ts
  src/domain/octree/OctreePacketProcessor.ts
Labels: enhancement, CR approved, QA approved

#126 Provide the domain's default avatar position.
  example/interface.html
  example/interface.js
  src/DomainServer.ts
  src/domain/interfaces/MyAvatarInterface.ts
  src/domain/networking/AddressManager.ts
  src/domain/networking/DomainHandler.ts
  src/domain/networking/NodeList.ts
  src/domain/networking/packets/DomainServerPathQuery.ts
  src/domain/networking/packets/DomainServerPathResponse.ts
  src/domain/networking/packets/PacketScribe.ts
  src/domain/networking/udt/PacketHeaders.ts
  src/domain/networking/udt/Socket.ts
  src/domain/shared/Quat.ts
  src/domain/shared/Url.ts
  src/domain/shared/Vec3.ts
  tests/domain/interfaces/MyAvatarInterface.unit.test.js
  tests/domain/networking/AddressManager.unit.test.js
  tests/domain/networking/DomainHandler.unit.test.js
  tests/domain/networking/packets/DomainServerPathQuery.unit.test.js
  tests/domain/networking/packets/DomainServerPathResponse.unit.test.js
  tests/domain/networking/packets/PacketScribe.unit.test.js
  tests/domain/networking/udt/PacketHeaders.unit.test.js
  tests/domain/networking/udt/Socket.integration.test.js
  tests/domain/networking/udt/Socket.unit.test.js
  tests/domain/shared/AvatarConstants.unit.test.js
  tests/domain/shared/Quat.unit.test.js
  tests/domain/shared/Url.unit.test.js
  tests/domain/shared/Vec3.unit.test.js
  tests/test.config.json
Labels: enhancement, CR approved, QA approved

#129 Bump version number and package files.
  package-lock.json
  package.json
Labels: housekeeping

#108 Provide Model entity data.
  example/interface.html
  example/interface.js
  package-lock.json
  package.json
  src/EntityServer.ts
  src/domain/ENTITY_SERVER.md
  src/domain/entities/EntityTypes.ts
  src/domain/networking/NLPacket.ts
  src/domain/networking/packets/EntityData.ts
  src/domain/octree/OctreePacketProcessor.ts
  src/domain/shared/AACube.ts
  src/domain/shared/ByteCountCoded.ts
  src/domain/shared/GLMHelpers.ts
  src/domain/shared/PropertyFlags.ts
  tests/domain/networking/NLPacket.unit.test.js
  tests/domain/networking/packets/EntityData.unit.test.js
  tests/domain/shared/ByteCountCoded.unit.test.js
  tests/domain/shared/GLMHelpers.unit.test.js
  tests/domain/shared/PropertyFlags.unit.test.js
Labels: enhancement, CR approved, QA approved

#134 Resolve entity packet reading details
  src/domain/networking/packets/EntityData.ts
Labels: CR approved, QA approved

#135 Provide Shape entity data.
  src/EntityServer.ts
  src/domain/entities/EntityPropertyFlags.ts
  src/domain/entities/EntityTypes.ts
  src/domain/entities/ModelEntityItem.ts
  src/domain/entities/ShapeEntityItem.ts
  src/domain/networking/packets/EntityData.ts
  src/domain/octree/OctreePacketProcessor.ts
  src/domain/shared/Color.ts
  tests/domain/entities/ModelEntityItem.unit.test.js
  tests/domain/entities/ShapeEntityItem.unit.test.js
  tests/domain/networking/packets/EntityData.unit.test.js
Labels: CR approved, QA approved

#142 Fix Model entity reading method
  src/domain/entities/ModelEntityItem.ts
  tests/domain/entities/ModelEntityItem.unit.test.js
Labels: bugfix, CR approved, QA approved

#143 Skip over unsupported entity types.
  example/interface.js
  src/domain/entities/AmbientLightPropertyGroup.ts
  src/domain/entities/BloomPropertyGroup.ts
  src/domain/entities/EntityPropertyFlags.ts
  src/domain/entities/GizmoEntityItem.ts
  src/domain/entities/GridEntityItem.ts
  src/domain/entities/HazePropertyGroup.ts
  src/domain/entities/ImageEntityItem.ts
  src/domain/entities/KeyLightPropertyGroup.ts
  src/domain/entities/LightEntityItem.ts
  src/domain/entities/LineEntityItem.ts
  src/domain/entities/MaterialEntityItem.ts
  src/domain/entities/ModelEntityItem.ts
  src/domain/entities/ParticleEffectEntityItem.ts
  src/domain/entities/PolyLineEntityItem.ts
  src/domain/entities/PolyVoxEntityItem.ts
  src/domain/entities/PulsePropertyGroup.ts
  src/domain/entities/RingGizmoPropertyGroup.ts
  src/domain/entities/ShapeEntityItem.ts
  src/domain/entities/SkyboxPropertyGroup.ts
  src/domain/entities/TextEntityItem.ts
  src/domain/entities/WebEntityItem.ts
  src/domain/entities/ZoneEntityItem.ts
  src/domain/networking/packets/EntityData.ts
  tests/domain/networking/packets/EntityData.unit.test.js
Labels: CR approved, QA approved

#145 Add Model and Shape entities support.
  example/interface.html
  example/interface.js
  package-lock.json
  package.json
  src/EntityServer.ts
  src/domain/ENTITY_SERVER.md
  src/domain/entities/AmbientLightPropertyGroup.ts
  src/domain/entities/BloomPropertyGroup.ts
  src/domain/entities/EntityPropertyFlags.ts
  src/domain/entities/EntityTypes.ts
  src/domain/entities/GizmoEntityItem.ts
  src/domain/entities/GridEntityItem.ts
  src/domain/entities/HazePropertyGroup.ts
  src/domain/entities/ImageEntityItem.ts
  src/domain/entities/KeyLightPropertyGroup.ts
  src/domain/entities/LightEntityItem.ts
  src/domain/entities/LineEntityItem.ts
  src/domain/entities/MaterialEntityItem.ts
  src/domain/entities/ModelEntityItem.ts
  src/domain/entities/ParticleEffectEntityItem.ts
  src/domain/entities/PolyLineEntityItem.ts
  src/domain/entities/PolyVoxEntityItem.ts
  src/domain/entities/PulsePropertyGroup.ts
  src/domain/entities/RingGizmoPropertyGroup.ts
  src/domain/entities/ShapeEntityItem.ts
  src/domain/entities/SkyboxPropertyGroup.ts
  src/domain/entities/TextEntityItem.ts
  src/domain/entities/WebEntityItem.ts
  src/domain/entities/ZoneEntityItem.ts
  src/domain/networking/NLPacket.ts
  src/domain/networking/packets/EntityData.ts
  src/domain/octree/OctreePacketProcessor.ts
  src/domain/shared/AACube.ts
  src/domain/shared/ByteCountCoded.ts
  src/domain/shared/Color.ts
  src/domain/shared/GLMHelpers.ts
  src/domain/shared/PropertyFlags.ts
  tests/domain/entities/ModelEntityItem.unit.test.js
  tests/domain/entities/ShapeEntityItem.unit.test.js
  tests/domain/networking/NLPacket.unit.test.js
  tests/domain/networking/packets/EntityData.unit.test.js
  tests/domain/shared/ByteCountCoded.unit.test.js
  tests/domain/shared/GLMHelpers.unit.test.js
  tests/domain/shared/PropertyFlags.unit.test.js
Labels: enhancement
