Repository vircadia/vircadia-web-sdk, pull requests merged in 2022-05, with the labels that each got.

#95 Set own avatar URL.
  example/interface.html
  example/interface.js
  src/AvatarMixer.ts
  src/domain/AvatarManager.ts
  src/domain/avatar-renderer/Avatar.ts
  src/domain/avatar-renderer/ScriptAvatar.ts
  src/domain/avatar/MyAvatar.ts
  src/domain/avatars/AvatarData.ts
  src/domain/avatars/AvatarTraits.ts
  src/domain/avatars/ClientTraitsHandler.ts
  src/domain/interfaces/MyAvatarInterface.ts
  src/domain/networking/packets/PacketScribe.ts
  src/domain/networking/packets/SetAvatarTraits.ts
  src/domain/networking/udt/PacketHeaders.ts
  tests/domain/avatars/AvatarTraits.unit.test.js
  tests/domain/avatars/ClientTraitsHandler.unit.test.js
  tests/domain/interfaces/MyAvatarInterface.unit.test.js
  tests/domain/networking/packets/PacketScribe.unit.test.js
  tests/domain/networking/packets/SetAvatarTraits.unit.test.js
Labels: enhancement, CR approved, QA approved

#98 Request entity data
  example/interface.js
  src/EntityServer.ts
  src/domain/networking/LimitedNodeList.ts
  src/domain/networking/packets/EntityQuery.ts
  src/domain/networking/packets/PacketScribe.ts
  src/domain/networking/udt/PacketHeaders.ts
  src/domain/octree/OctreeConstants.ts
  src/domain/octree/OctreeQuery.ts
  src/domain/shared/ConicalViewFrustum.ts
  src/domain/shared/GLMHelpers.ts
  tests/domain/networking/packets/EntityQuery.unit.test.js
  tests/domain/shared/GLMHelpers.unit.test.js
Labels: CR approved, QA approved

#97 Request avatar data
  example/interface.html
  example/interface.js
  src/AvatarMixer.ts
  src/Camera.ts
  src/Vircadia.ts
  src/domain/avatars/AvatarData.ts
  src/domain/networking/packets/AvatarQuery.ts
  src/domain/networking/packets/PacketScribe.ts
  src/domain/networking/udt/PacketHeaders.ts
  src/domain/shared/Camera.ts
  src/domain/shared/GLMHelpers.ts
  src/domain/shared/Vec3.ts
  tests/AvatarMixer.integration.test.js
  tests/AvatarMixer.unit.test.js
  tests/Camera.unit.test.js
  tests/Vircadia.integration.test.js
  tests/domain/networking/packets/AvatarQuery.unit.test.js
  tests/domain/networking/packets/PacketScribe.unit.test.js
  tests/domain/shared/Camera.unit.test.js
  tests/domain/shared/GLMHelpers.unit.test.js
  tests/domain/shared/Vec3.unit.test.js
Labels: enhancement, CR approved, QA approved

#104 Address repo line endings.
  .editorconfig
  CODING_STANDARD.md
  README.md
Labels: bugfix, CR approved

#105 Receive entity server packets.
  src/EntityServer.ts
  src/domain/networking/PacketReceiver.ts
  src/domain/octree/OctreePacketProcessor.ts
  src/domain/octree/OctreeQuery.ts
  src/domain/shared/ContextManager.ts
  tests/domain/networking/PacketReceiver.unit.test.js
  tests/domain/octree/OctreePacketProcessor.unit.test.js
Labels: enhancement, CR approved, QA approved

#106 Handle entity data packets.
  src/DomainServer.ts
  src/EntityServer.ts
  src/domain/networking/packets/EntityData.ts
  src/domain/networking/packets/PacketScribe.ts
  src/domain/networking/udt/PacketHeaders.ts
  src/domain/octree/OctreePacketProcessor.ts
Labels: enhancement, CR approved, QA approved
