Repository vircadia/vircadia-web-sdk, pull requests merged in 2022-04, with the labels that each got.

#91 Fix trailing 0s being sent in NLPacketList packets.
  src/domain/networking/MessageData.ts
  src/domain/networking/NLPacketList.ts
  tests/domain/networking/packets/AvatarIdentity.unit.test.js
  tests/domain/networking/packets/MessagesData.unit.test.js
  tests/domain/networking/packets/MessagesSubscribe.unit.test.js
  tests/domain/networking/packets/MessagesUnsubscribe.unit.test.js
Labels: bugfix, QA approved

#92 Add EntityServer design document.
  src/domain/ENTITY_SERVER.md
Labels: enhancement

#93 Add entity server class
  example/interface.html
  example/interface.js
  src/DomainServer.ts
  src/EntityServer.ts
  src/Vircadia.ts
  tests/EntityServer.integration.test.js
  tests/EntityServer.unit.test.js
  tests/Vircadia.integration.test.js
Labels: CR approved, QA approved

#94 Fix erroneous spaces in C++ comments.
  src/DomainServer.ts
  src/domain/avatars/AvatarHashMap.ts
  src/domain/networking/NLPacket.ts
  src/domain/networking/packets/MicrophoneAudioNoEcho.ts
  src/domain/networking/packets/SilentAudioFrame.ts
  src/domain/networking/udt/ControlPacket.ts
  src/domain/shared/GLMHelpers.ts
Labels: bugfix
