Repository vircadia/vircadia-web-sdk, pull requests merged in 2022-06, with the labels that each got.

#109 Provide skeleton data for other users' avatars.
  example/interface.html
  example/interface.js
  src/domain/avatar-renderer/ScriptAvatar.ts
  src/domain/avatars/AvatarData.ts
  src/domain/avatars/AvatarTraits.ts
  src/domain/networking/packets/BulkAvatarData.ts
  src/domain/shared/GLMHelpers.ts
  tests/domain/networking/packets/BulkAvatarTraits.unit.test.js
  tests/domain/shared/GLMHelpers.unit.test.js
Labels: enhancement

#110 Provide avatar scale for other users' avatars
  example/interface.html
  example/interface.js
  src/domain/avatar-renderer/ScriptAvatar.ts
  src/domain/avatars/AvatarData.ts
  src/domain/avatars/AvatarHashMap.ts
  src/domain/networking/packets/BulkAvatarData.ts
  src/domain/shared/AvatarConstants.ts
  tests/domain/avatar-renderer/ScriptAvatar.unit.test.js
  tests/domain/avatars/AvatarData.unit.test.js
  tests/domain/networking/packets/BulkAvatarData.unit.test.js
  tests/domain/networking/packets/SetAvatarTraits.unit.test.js
Labels: enhancement

#111 Provide avatar joint data for others' avatars.
  example/interface.html
  example/interface.js
  src/domain/avatar-renderer/ScriptAvatar.ts
  src/domain/avatars/AvatarData.ts
  src/domain/avatars/AvatarHashMap.ts
  src/domain/networking/packets/BulkAvatarData.ts
  tests/domain/avatar-renderer/ScriptAvatar.unit.test.js
  tests/domain/networking/packets/BulkAvatarData.unit.test.js
Labels: enhancement

#113 Enable sending own avatar skeleton to avatar mixer.
  example/interface.js
  src/domain/avatar-renderer/ScriptAvatar.ts
  src/domain/avatars/AvatarData.ts
  src/domain/avatars/AvatarTraits.ts
  src/domain/avatars/ClientTraitsHandler.ts
  src/domain/interfaces/MyAvatarInterface.ts
  src/domain/networking/NLPacketList.ts
  src/domain/networking/packets/BulkAvatarData.ts
  src/domain/networking/packets/SetAvatarTraits.ts
  src/domain/shared/Quat.ts
  src/domain/shared/Vec3.ts
  tests/domain/avatar-renderer/ScriptAvatar.unit.test.js
  tests/domain/interfaces/MyAvatarInterface.unit.test.js
  tests/domain/networking/packets/SetAvatarTraits.unit.test.js
Labels: enhancement

#117 Add ability to send own avatar joint data to avatar mixer.
  example/interface.html
  example/interface.js
  src/domain/audio/AudioWorklets.ts
  src/domain/avatar-renderer/ScriptAvatar.ts
  src/domain/avatars/AvatarData.ts
  src/domain/interfaces/AvatarListInterface.ts
  src/domain/interfaces/MyAvatarInterface.ts
  src/domain/networking/packets/AvatarData.ts
  src/domain/networking/packets/BulkAvatarData.ts
  src/domain/octree/OctreeConstants.ts
  src/domain/shared/BitVectorHelpers.ts
  src/domain/shared/Quat.ts
  tests/domain/avatar-renderer/ScriptAvatar.unit.test.js
  tests/domain/networking/packets/AvatarData.unit.test.js
  tests/domain/networking/packets/BulkAvatarData.unit.test.js
  tests/domain/shared/BitVectorHelpers.unit.test.js
  tests/domain/shared/Quat.unit.test.js
Labels: enhancement, bugfix, CR approved, QA approved

#118 Fix skipping deleting an instanced trait when reading BulkAvatarTraits message.
  src/domain/avatars/AvatarTraits.ts
  src/domain/networking/packets/BulkAvatarTraits.ts
  tests/domain/avatars/AvatarTraits.unit.test.js
  tests/domain/networking/packets/BulkAvatarData.unit.test.js
  tests/domain/networking/packets/BulkAvatarTraits.unit.test.js
Labels: bugfix, CR approved, QA approved

#119 Replace non-functioning STUN server address.
  src/domain/networking/webrtc/WebRTCDataChannel.ts
Labels: bugfix

#120 Update README.md.
  README.md
Labels: documentation
