Repository vircadia/vircadia-web-sdk, pull requests merged in 2023-02, with the labels that each got.

#237 Double the received audio jitter buffer size.
  src/domain/audio-client/AudioClient.ts
  src/domain/worklets/AudioOutputProcessor.ts
Labels: CR approved, QA approved

#238 Ramp audio packet volume up/down on either side of silent samples.
  src/domain/audio/InboundAudioStream.ts
Labels: enhancement, needs QA (testing), QA approved

#257 Fix UsersInterface.kick() user doc.
  src/domain/interfaces/UsersInterface.ts
Labels: documentation

#258 Add fingerprint code for browser environment.
  .gitignore
  src/domain/networking/FingerprintUtils.ts
  src/domain/shared/ModerationFlags.ts
  tests/domain/networking/FingerprintUtils.unit.test.js
  tests/domain/shared/Uuid.unit.test.js
Labels: enhancement, CR approved

#260 Update contributors list.
  package.json
Labels: housekeeping

#262 Housekeeping.
  package-lock.json
  src/domain/audio-client/AudioClient.ts
Labels: housekeeping

#261 Fix lint error.
  package-lock.json
  src/domain/audio-client/AudioClient.ts
Labels: housekeeping

#263 Fix tests.
  tests/AudioMixer.integration.test.js
  tests/AudioMixer.unit.test.js
  tests/AvatarMixer.integration.test.js
  tests/AvatarMixer.unit.test.js
  tests/Camera.unit.test.js
  tests/DomainServer.integration.test.js
  tests/DomainServer.unit.test.js
  tests/EntityServer.integration.test.js
  tests/EntityServer.unit.test.js
  tests/MessageMixer.integration.test.js
  tests/MessageMixer.unit.test.js
  tests/Vircadia.integration.test.js
  tests/Vircadia.unit.test.js
  tests/domain/AssignmentClient.integration.test.js
  tests/domain/AssignmentClient.unit.test.js
  tests/domain/audio-client/AudioClient.unit.test.js
  tests/domain/audio/InboundAudioStream.unit.test.js
  tests/domain/avatar-renderer/Avatar.unit.test.js
  tests/domain/avatar-renderer/ScriptAvatar.unit.test.js
  tests/domain/avatar/MyAvatar.unit.test.js
  tests/domain/avatars/AvatarData.unit.test.js
  tests/domain/avatars/AvatarTraits.unit.test.js
  tests/domain/avatars/ClientTraitsHandler.unit.test.js
  tests/domain/interfaces/AccountInterface.unit.test.js
  tests/domain/interfaces/AvatarListInterface.unit.test.js
  tests/domain/interfaces/MyAvatarInterface.unit.test.js
  tests/domain/interfaces/UsersInterface.unit.test.js
  tests/domain/networking/AccountManager.integration.test.js
  tests/domain/networking/AccountManager.unit.test.js
  tests/domain/networking/DataServerAccountInfo.unit.test.js
  tests/domain/networking/DomainHandler.unit.test.js
  tests/domain/networking/LimitedNodeList.unit.test.js
  tests/domain/networking/MessagesClient.unit.test.js
  tests/domain/networking/NodeList.unit.test.js
  tests/domain/networking/PacketReceiver.unit.test.js
  tests/domain/networking/packets/AvatarData.unit.test.js
  tests/domain/networking/packets/BulkAvatarTraits.unit.test.js
  tests/domain/networking/packets/DomainConnectRequest.unit.test.js
  tests/domain/networking/packets/DomainConnectionDenied.unit.test.js
  tests/domain/networking/packets/PacketScribe.unit.test.js
  tests/domain/networking/packets/SetAvatarTraits.unit.test.js
  tests/domain/octree/OctreePacketProcessor.unit.test.js
  tests/domain/shared/SpatiallyNestable.unit.test.js
  tests/domain/shared/Uuid.unit.test.js
Labels: bugfix

#264 Fix npm install peer dependency errors.
  CONFIGURATION.md
  package-lock.json
  package.json
  tests/AudioMixer.integration.test.js
  tests/AvatarMixer.integration.test.js
  tests/DomainServer.integration.test.js
  tests/EntityServer.integration.test.js
  tests/MessageMixer.integration.test.js
  tests/domain/AssignmentClient.integration.test.js
  tests/domain/networking/udt/Socket.integration.test.js
  tests/domain/networking/webrtc/WebRTCDataChannel.integration.test.js
  tests/domain/networking/webrtc/WebRTCSignalingChannel.integration.test.js
  tests/domain/networking/webrtc/WebRTCSocket.integration.test.js
Labels: bugfix

#265 Fix version number.
  package.json
Labels: bugfix
